-- Réécriture des scripts d’entretien (section « methodologie ») pour le mode
-- pas à pas : une phase = un moment de l’entretien, une étape = une consigne
-- courte avec, si utile, la phrase-clé à dire. Sources : voir
-- scripts/RAPPORT-scripts-entretiens-pas-a-pas-2026-09-29.md.
--
-- Périmètre : uniquement les types de « Pharmacie Rome Village » (seule
-- officine qui avait du contenu). La section « facturation » n’est pas touchée.
--
-- Sauvegarde : l’ancien contenu est copié dans
-- public.entretien_items_sauvegarde_20260929 (RLS activée, aucune policy : lisible
-- seulement via le service role / l’éditeur SQL). Pour revenir en arrière :
--   delete from entretien_items ei using types_entretien te, officines o
--    where ei.type_entretien_id = te.id and te.officine_id = o.id
--      and o.nom = 'Pharmacie Rome Village' and ei.section = 'methodologie';
--   insert into entretien_items select * from entretien_items_sauvegarde_20260929;

create table if not exists public.entretien_items_sauvegarde_20260929 as
  select ei.* from public.entretien_items ei
  where ei.section = 'methodologie';

alter table public.entretien_items_sauvegarde_20260929 enable row level security;

delete from public.entretien_items ei
using public.types_entretien te, public.officines o
where ei.type_entretien_id = te.id
  and te.officine_id = o.id
  and o.nom = 'Pharmacie Rome Village'
  and ei.section = 'methodologie';

-- Lignes : [clé du type, phase, code du type d’item, contenu].
-- Code : q = question, e = explication, a = alerte, chaîne vide = non typé (consigne).
insert into public.entretien_items (type_entretien_id, section, contenu, ordre, phase, type_item)
select
  tc.type_id,
  'methodologie',
  s.elem->>3,
  (row_number() over (partition by tc.type_id order by s.ord) - 1)::int,
  s.elem->>1,
  case s.elem->>2 when 'q' then 'question' when 'e' then 'explication' when 'a' then 'alerte' else null end
from jsonb_array_elements($json$[
    ["avk","Évaluation · Accueil","e","Présenter l’objectif : faire connaître le traitement, vérifier sa bonne prise et définir avec le patient un programme d’entretiens thématiques."],
    ["avk","Évaluation · Accueil","","Recevoir le patient dans l’espace de confidentialité et vérifier son accord (bulletin d’adhésion signé)."],
    ["avk","Évaluation · Recueil","","Relever l’AVK prescrit, la posologie, la date de début et les prescripteurs."],
    ["avk","Évaluation · Recueil","","Relever les autres traitements au long cours et les médicaments ou compléments pris sans ordonnance."],
    ["avk","Évaluation · Recueil","","Noter l’historique des AVK : molécules, dates, changements de traitement, accidents éventuels."],
    ["avk","Évaluation · Recueil","","Vérifier l’absence de contre-indication absolue ou relative (RCP) et noter le laboratoire qui dose l’INR."],
    ["avk","Évaluation · Recueil","q","Quelles sont vos habitudes de vie : alimentation, alcool, tabac, activité physique, sport de contact, bricolage, jardinage, voyages ?"],
    ["avk","Évaluation · Recueil","","Repérer les difficultés motrices, cognitives ou sensorielles qui nécessitent une aide. Vérifier si le patient a un carnet de suivi AVK."],
    ["avk","Évaluation · Appropriation du traitement","q","Comment vivez-vous globalement votre traitement ?"],
    ["avk","Évaluation · Appropriation du traitement","q","À quoi sert votre traitement AVK ? Pourquoi vous l’a-t-on prescrit ?"],
    ["avk","Évaluation · Appropriation du traitement","q","Savez-vous que ce traitement présente des risques ? Lesquels ?"],
    ["avk","Évaluation · Appropriation du traitement","q","Savez-vous qu’il demande une surveillance biologique (INR) ?"],
    ["avk","Évaluation · Appropriation du traitement","","Pour chaque réponse, noter : acquis, partiellement acquis ou non acquis."],
    ["avk","Évaluation · Observance","q","Connaissez-vous la dose prescrite par votre médecin ? La respectez-vous ?"],
    ["avk","Évaluation · Observance","q","À quelle heure prenez-vous ce médicament ? Le prenez-vous tous les jours à la même heure ?"],
    ["avk","Évaluation · Observance","q","Vous arrive-t-il d’oublier votre traitement ? Que faites-vous dans ce cas ?"],
    ["avk","Évaluation · Observance","e","En cas d’oubli : la dose peut être prise dans les 8 heures suivant l’heure habituelle, au-delà on saute la prise. Jamais de dose double. Noter l’oubli dans le carnet et prévenir le médecin."],
    ["avk","Évaluation · Observance","q","Notez-vous vos prises et vos oublis éventuels dans le carnet de suivi ?"],
    ["avk","Évaluation · Coordination","q","Quels autres professionnels de santé voyez-vous ? Leur présentez-vous la carte « Je prends un traitement par AVK » ?"],
    ["avk","Évaluation · Coordination","e","Prévenir le médecin avant toute intervention, même bénigne (petite chirurgie, extraction dentaire), et en cas de changement de situation."],
    ["avk","Évaluation · Coordination","a","Grossesse : les AVK sont à éviter sauf cas très particulier. Contraception efficace pendant le traitement et jusqu’à 3 jours (acénocoumarol), 7 jours (fluindione) ou 10 jours (warfarine) après l’arrêt. Si grossesse suspectée : prévenir le médecin, sans arrêter l’AVK de soi-même."],
    ["avk","Évaluation · Clôture","q","Avez-vous des questions ou des remarques ?"],
    ["avk","Évaluation · Clôture","","Compléter le bilan de l’entretien et le plan d’accompagnement (entretiens à programmer selon les points non acquis)."],
    ["avk","Évaluation · Clôture","","Fixer les prochains rendez-vous : surveillance biologique, observance, effets du traitement, vie quotidienne et alimentation."],
    ["avk","Thème · Surveillance biologique","e","L’INR mesure l’action de l’AVK sur la fluidité du sang. Cet examen est indispensable pendant toute la durée du traitement."],
    ["avk","Thème · Surveillance biologique","q","Connaissez-vous votre INR cible et sa fourchette ? Sont-ils notés dans votre carnet ?"],
    ["avk","Thème · Surveillance biologique","e","Contrôle au moins une fois par mois (plus souvent au début), le matin. Récupérer le résultat le jour même, le noter dans le carnet et le transmettre au médecin."],
    ["avk","Thème · Surveillance biologique","a","INR hors de la fourchette : au-dessus, risque de saignement ; en dessous, risque de caillot. Prévenir le médecin sans attendre."],
    ["avk","Thème · Surveillance biologique","e","Un contrôle supplémentaire est nécessaire après un nouveau médicament ou un changement d’alimentation."],
    ["avk","Thème · Observance","q","Prenez-vous votre AVK chaque jour à la même heure (de préférence le soir) ?"],
    ["avk","Thème · Observance","e","Toute modification de dose est décidée par le médecin, jamais par le patient."],
    ["avk","Thème · Observance","q","Remplissez-vous le carnet à chaque INR (résultat, dose prise, incident) ?"],
    ["avk","Thème · Observance","e","En déplacement : emporter l’ordonnance, le traitement en quantité suffisante et le carnet ; garder le traitement en cabine ; décalage horaire : demander conseil au médecin."],
    ["avk","Thème · Observance","e","Conserver les comprimés dans leur emballage d’origine et y replacer les fractions non utilisées juste après la découpe."],
    ["avk","Thème · Effets du traitement","q","Avez-vous eu un saignement, des bleus ou d’autres effets depuis notre dernier entretien ?"],
    ["avk","Thème · Effets du traitement","a","Saignement même minime (gencives, nez, œil rouge, sang dans les urines ou les selles, selles noires, règles abondantes, hématomes, vomissements ou crachats sanglants, saignement qui ne s’arrête pas) : contacter rapidement un médecin."],
    ["avk","Thème · Effets du traitement","a","Signes d’un saignement interne (fatigue ou essoufflement inhabituels, pâleur, mal de tête persistant, malaise inexpliqué) : consulter."],
    ["avk","Thème · Vie quotidienne et alimentation","e","Les aliments riches en vitamine K (brocolis, asperges, épinards, choux, endives, salade frisée…) ne sont pas interdits : les répartir régulièrement, sans excès. Alcool avec modération."],
    ["avk","Thème · Vie quotidienne et alimentation","a","Aucun autre médicament sans avis (aspirine, anti-inflammatoires, millepertuis…), même vendu sans ordonnance. Paracétamol : pas plus de 4 jours à 4 g par jour."],
    ["avk","Thème · Vie quotidienne et alimentation","e","Signaler l’AVK à tout professionnel de santé. Avis médical avant extraction dentaire, injection, petite chirurgie, pédicurie ou voyage."],
    ["avk","Thème · Vie quotidienne et alimentation","e","Éviter les sports violents et les travaux pouvant entraîner une coupure ou une chute."],

    ["aod","Évaluation · Accueil","e","Présenter l’objectif : faire connaître le traitement, vérifier sa bonne prise et définir avec le patient un programme d’entretiens thématiques."],
    ["aod","Évaluation · Accueil","","Recevoir le patient dans l’espace de confidentialité et vérifier son accord (bulletin d’adhésion signé)."],
    ["aod","Évaluation · Recueil","","Relever l’AOD prescrit, la posologie, la date de début et les prescripteurs, ainsi que les autres médicaments au long cours et les compléments pris."],
    ["aod","Évaluation · Recueil","","Noter l’historique des anticoagulants oraux : molécules, dates, changements, accidents éventuels liés au traitement."],
    ["aod","Évaluation · Recueil","","Vérifier l’absence de contre-indication au traitement."],
    ["aod","Évaluation · Recueil","q","Quelles sont vos habitudes de vie, notamment vos activités ou sports à risque ?"],
    ["aod","Évaluation · Recueil","","Repérer les difficultés motrices, cognitives ou sensorielles qui nécessitent une aide. Vérifier le document du patient (carnet de suivi ou carte AOD)."],
    ["aod","Évaluation · Appropriation du traitement","q","Comment vivez-vous globalement votre traitement ?"],
    ["aod","Évaluation · Appropriation du traitement","q","À quoi sert votre médicament ? Pourquoi vous l’a-t-on prescrit ?"],
    ["aod","Évaluation · Appropriation du traitement","q","Savez-vous que ce traitement présente des risques ? Lesquels ?"],
    ["aod","Évaluation · Appropriation du traitement","","Pour chaque réponse, noter : acquis, partiellement acquis ou non acquis."],
    ["aod","Évaluation · Observance","q","Connaissez-vous la dose prescrite par votre médecin ? La respectez-vous ?"],
    ["aod","Évaluation · Observance","q","À quel moment prenez-vous ce médicament ? Le prenez-vous chaque jour à la même heure ?"],
    ["aod","Évaluation · Observance","e","Xarelto 15 mg et 20 mg : à prendre avec des aliments."],
    ["aod","Évaluation · Coordination","q","Quels autres professionnels de santé voyez-vous ? Leur présentez-vous la carte « Je prends un traitement anticoagulant par AOD » ?"],
    ["aod","Évaluation · Coordination","e","Prévenir le médecin avant toute intervention, même bénigne (petite chirurgie, extraction dentaire), et en cas de changement de situation (grossesse…)."],
    ["aod","Évaluation · Clôture","q","Avez-vous des questions ou des remarques ?"],
    ["aod","Évaluation · Clôture","","Compléter le bilan de l’entretien et le plan d’accompagnement (entretiens à programmer selon les points non acquis)."],
    ["aod","Évaluation · Clôture","","Fixer les prochains rendez-vous : observance, surveillance biologique, effets du traitement, vie quotidienne et alimentation."],
    ["aod","Thème · Observance","q","Prenez-vous votre AOD chaque jour à la même heure ? Avez-vous eu des oublis ?"],
    ["aod","Thème · Observance","e","En cas d’oubli, la conduite à tenir dépend de la molécule : la rappeler avec la notice de l’AOD prescrit. Ne jamais prendre de dose double."],
    ["aod","Thème · Surveillance biologique","e","Contrairement aux AVK, il n’y a pas de contrôle d’INR : le suivi biologique (dont la fonction rénale) est fixé par le médecin selon le patient."],
    ["aod","Thème · Surveillance biologique","q","Avez-vous fait vos prises de sang prescrites ? Avez-vous votre carnet et votre carte AOD sur vous ?"],
    ["aod","Thème · Effets du traitement","q","Avez-vous eu un saignement, des bleus ou d’autres effets depuis notre dernier entretien ?"],
    ["aod","Thème · Effets du traitement","a","Saignement (gencives, nez, urines, selles noires ou sanglantes, règles abondantes, vomissements ou crachats sanglants, saignement qui ne s’arrête pas) ou signe de saignement interne (fatigue, pâleur, essoufflement, mal de tête persistant, malaise) : contacter rapidement un médecin."],
    ["aod","Thème · Vie quotidienne et alimentation","e","Aucun autre médicament sans avis (aspirine, anti-inflammatoires, plantes comme le millepertuis), même sans ordonnance."],
    ["aod","Thème · Vie quotidienne et alimentation","e","Signaler l’AOD à tout professionnel de santé. Avis médical avant extraction dentaire, injection, petite chirurgie ou voyage."],
    ["aod","Thème · Vie quotidienne et alimentation","e","Éviter les sports violents et les travaux pouvant entraîner une coupure ou une chute."],

    ["asthme","Évaluation · Accueil","e","Présenter l’objectif : faire comprendre le traitement, définir avec le patient un programme d’entretiens thématiques."],
    ["asthme","Évaluation · Accueil","","Recevoir le patient dans l’espace de confidentialité, faire signer le bulletin d’adhésion et créer son dossier pharmaceutique s’il n’existe pas."],
    ["asthme","Évaluation · Recueil","","Relever les médicaments prescrits, les posologies et la date de début, ainsi que le médecin traitant ou le pneumologue."],
    ["asthme","Évaluation · Recueil","","Repérer les difficultés motrices, cognitives ou sensorielles. Vérifier les documents du patient (plan d’action, auto-questionnaire, peak-flow)."],
    ["asthme","Évaluation · Recueil","q","Avez-vous suivi ou suivez-vous un programme d’éducation thérapeutique (école de l’asthme) ?"],
    ["asthme","Évaluation · Compréhension du traitement","q","Comment vivez-vous votre asthme ?"],
    ["asthme","Évaluation · Compréhension du traitement","q","Savez-vous pourquoi votre traitement vous est prescrit ? Savez-vous nommer votre traitement de fond et votre traitement de crise ?"],
    ["asthme","Évaluation · Compréhension du traitement","e","L’asthme est une maladie chronique, inflammatoire et obstructive des bronches : au contact d’un élément irritant, les muscles bronchiques se contractent et s’enflamment, ce qui gêne la respiration."],
    ["asthme","Évaluation · Compréhension du traitement","e","Traitement de fond : réduit l’inflammation et prévient les crises. Effet ressenti après 7 à 14 jours. À prendre tous les jours, aux mêmes heures, même sans symptôme. Ne jamais l’arrêter sans avis médical."],
    ["asthme","Évaluation · Compréhension du traitement","e","Traitement de crise : relâche les muscles bronchiques, effet en 5 à 10 minutes. À prendre à la demande dès les symptômes ou avant un effort, et à avoir toujours sur soi."],
    ["asthme","Évaluation · Compréhension du traitement","q","Quelle est votre posologie pour le traitement de fond, et pour la crise ?"],
    ["asthme","Évaluation · Compréhension du traitement","q","Prenez-vous régulièrement votre traitement de fond ?"],
    ["asthme","Évaluation · Compréhension du traitement","a","Traitement de crise utilisé plus de 2 fois par semaine : signe d’aggravation, souvent lié à une mauvaise prise du traitement de fond. À signaler au médecin."],
    ["asthme","Évaluation · Compréhension du traitement","","Pour chaque réponse, noter : acquis, partiellement acquis ou non acquis."],
    ["asthme","Évaluation · Clôture","q","Avez-vous des questions ou des remarques ?"],
    ["asthme","Évaluation · Clôture","","Rédiger la synthèse et la durée de l’entretien, apprécier le niveau de connaissance du patient."],
    ["asthme","Évaluation · Clôture","","Noter si un accompagnant sera présent au prochain entretien. Orienter le patient vers son prescripteur, voire le contacter, si besoin."],
    ["asthme","Évaluation · Clôture","","Fixer les prochains rendez-vous : principes du traitement, technique d’inhalation, effets du traitement, observance, facteurs déclencheurs."],
    ["asthme","Thème · Technique d’inhalation","","Demander au patient de faire la prise avec son propre dispositif, sans l’aider, et observer chaque geste."],
    ["asthme","Thème · Technique d’inhalation","","Corriger les gestes erronés en refaisant la démonstration, puis faire répéter jusqu’à ce que la technique soit acquise."],
    ["asthme","Thème · Technique d’inhalation","","Vérifier la quantité de produit restant dans le dispositif (comparer la posologie et le nombre de doses)."],
    ["asthme","Thème · Effets du traitement","e","Après un corticoïde inhalé : se rincer la bouche pour limiter les effets locaux."],
    ["asthme","Thème · Effets du traitement","q","Avez-vous remarqué un mauvais goût, un enrouement ou une toux après l’inhalation ?"],
    ["asthme","Thème · Observance","q","Combien de fois par semaine utilisez-vous votre traitement de crise ?"],
    ["asthme","Thème · Observance","q","Vous arrive-t-il d’oublier ou d’arrêter votre traitement de fond quand vous vous sentez bien ?"],
    ["asthme","Thème · Facteurs déclencheurs","q","Qu’est-ce qui déclenche vos crises (effort, allergènes, tabac, pollution, infections) ?"],
    ["asthme","Thème · Facteurs déclencheurs","e","Rappeler les moyens d’éviter chaque facteur déclencheur repéré, et la prise du traitement de crise avant un effort si besoin."],

    ["onco","Entretien 1 · Accueil et recueil","","Recevoir le patient dans l’espace de confidentialité, vérifier son accord (bulletin d’adhésion « anticancéreux par voie orale » signé). Adapter le discours à sa connaissance de la maladie et à son acceptation."],
    ["onco","Entretien 1 · Accueil et recueil","","Relever le ou les anticancéreux oraux prescrits, les autres traitements au long cours et les produits pris sans ordonnance (compléments, aromathérapie…)."],
    ["onco","Entretien 1 · Accueil et recueil","","Noter les habitudes de vie, les allergies et intolérances, les situations nécessitant une aide, ainsi que les coordonnées du médecin traitant et du service d’oncologie."],
    ["onco","Entretien 1 · Appropriation du traitement","q","Comment percevez-vous votre traitement ? Que savez-vous de ce traitement ?"],
    ["onco","Entretien 1 · Appropriation du traitement","q","Comment vivez-vous le fait de prendre ce traitement par voie orale, à domicile ?"],
    ["onco","Entretien 1 · Appropriation du traitement","q","Votre médecin traitant sait-il que vous prenez un anticancéreux oral ?"],
    ["onco","Entretien 1 · Appropriation du traitement","q","Savez-vous pourquoi il est important de bien suivre ce traitement et de le faire surveiller ?"],
    ["onco","Entretien 1 · Schéma et règles de prise","","Remettre un plan de posologie précisant les cycles, les moments de prise et les arrêts. Contacter le service d’oncologie en cas de doute sur le schéma."],
    ["onco","Entretien 1 · Schéma et règles de prise","e","Règles de prise : ne pas ouvrir les gélules, ne pas écraser, mâcher, sucer ou couper les comprimés ; se laver les mains après manipulation. Se référer à la fiche de la molécule pour le moment de prise."],
    ["onco","Entretien 1 · Schéma et règles de prise","e","Conservation : dans l’emballage d’origine (pas de pilulier), au sec, à l’abri de la lumière et hors de portée des enfants."],
    ["onco","Entretien 1 · Schéma et règles de prise","e","Oubli ou surdosage : la conduite à tenir dépend de chaque molécule (voir la fiche). En cas de prise excessive, contacter le médecin avant la prochaine dose."],
    ["onco","Entretien 1 · Schéma et règles de prise","a","Pas d’automédication : demander l’avis du médecin ou du pharmacien avant tout médicament, même sans ordonnance (interactions). Rappeler les contre-indications alimentaires, vaccinales et médicamenteuses."],
    ["onco","Entretien 1 · Clôture","q","Avez-vous des questions ou des remarques ?"],
    ["onco","Entretien 1 · Clôture","","Surveillance attentive du premier cycle : fixer le prochain rendez-vous. Rédiger la synthèse de l’entretien."],
    ["onco","Entretien 2 · Effets indésirables et vie quotidienne","q","Depuis le dernier entretien, avez-vous ressenti des effets gênants (fatigue, nausées, diarrhée, aphtes, peau…) ?"],
    ["onco","Entretien 2 · Effets indésirables et vie quotidienne","e","Rappeler la conduite à tenir devant chaque effet indésirable de la molécule (fiche de la molécule, fiches INCa ou OMEDIT) et quand appeler le médecin ou le service d’oncologie."],
    ["onco","Entretien 2 · Effets indésirables et vie quotidienne","q","Rencontrez-vous des difficultés dans votre vie quotidienne (alimentation, travail, déplacements, vie sociale) ?"],
    ["onco","Entretien 2 · Effets indésirables et vie quotidienne","","Faire le point sur les analyses de suivi et les vaccins avec le patient."],
    ["onco","Entretien 3 · Observance","q","Comment se passent les prises ? Avez-vous eu des oublis, des doses en trop ou des arrêts de votre initiative ?"],
    ["onco","Entretien 3 · Observance","q","Qu’est-ce qui vous aiderait à mieux suivre le traitement (aide-mémoire, rappels, pilulier dédié…) ?"],
    ["onco","Entretien 3 · Observance","","Vérifier les acquis des entretiens précédents et signaler au prescripteur toute difficulté d’observance."],

    ["bpm","Entretien de recueil · Accueil","e","Présenter le bilan de médication : son objectif, son déroulement, et le fait que les informations seront partagées avec le médecin traitant."],
    ["bpm","Entretien de recueil · Accueil","","Recevoir le patient dans l’espace de confidentialité, vérifier son accord (formulaire d’adhésion) et relever l’identité, l’âge, le poids et le médecin traitant."],
    ["bpm","Entretien de recueil · Habitudes de vie","q","Vivez-vous seul(e) chez vous ou en institution ? Quelqu’un vous aide-t-il au quotidien ?"],
    ["bpm","Entretien de recueil · Habitudes de vie","q","Quelles sont vos habitudes alimentaires (nombre de repas, horaires, collations) ? Suivez-vous un régime particulier ?"],
    ["bpm","Entretien de recueil · Habitudes de vie","q","Consommez-vous de l’alcool ou du pamplemousse ?"],
    ["bpm","Entretien de recueil · État physiologique","q","Souffrez-vous d’une maladie rénale ou hépatique, ou d’un autre antécédent identifié ?"],
    ["bpm","Entretien de recueil · État physiologique","q","Avez-vous des problèmes de déglutition, de vision, des douleurs articulaires ?"],
    ["bpm","Entretien de recueil · État physiologique","q","Avez-vous des allergies ? Avez-vous un carnet de suivi ?"],
    ["bpm","Entretien de recueil · État physiologique","a","Repérer les signes d’alerte : chute dans les 3 derniers mois, troubles du sommeil, somnolence en journée, perte de poids de plus de 4,5 kg dans l’année, perte d’appétit, incontinence urinaire."],
    ["bpm","Entretien de recueil · Traitements","","Pour chaque médicament, relever : produit, dosage et forme, posologie, origine (prescription ou automédication), problème de forme galénique, problème d’observance, effets indésirables."],
    ["bpm","Entretien de recueil · Traitements","q","Pouvez-vous m’expliquer à quoi servent vos médicaments ? À quelle fréquence et quand les prenez-vous ?"],
    ["bpm","Entretien de recueil · Traitements","q","Prenez-vous d’autres produits par vous-même (aromathérapie, phytothérapie, médicaments sans ordonnance, crèmes, vitamines, collyres, compléments) ? Avez-vous pris des antibiotiques récemment ?"],
    ["bpm","Entretien de recueil · Traitements","q","Avez-vous récemment arrêté ou modifié un traitement prescrit ? Pourquoi ?"],
    ["bpm","Entretien de recueil · Traitements","q","Ressentez-vous des effets particuliers liés à vos médicaments (somnolence, douleurs articulaires) ? Avez-vous déjà eu des effets indésirables ?"],
    ["bpm","Entretien de recueil · Traitements","q","Prenez-vous un médicament qui nécessite un suivi particulier (antidiabétique, anticoagulant…) ?"],
    ["bpm","Entretien de recueil · Prise des médicaments","q","À quel moment de la journée prenez-vous vos médicaments ? Avez-vous des rappels pour y penser ?"],
    ["bpm","Entretien de recueil · Prise des médicaments","q","Vous reste-t-il des médicaments dans les boîtes à la fin du mois ? Êtes-vous parfois en rupture ? En avez-vous en grande quantité chez vous ?"],
    ["bpm","Entretien de recueil · Prise des médicaments","q","Avez-vous tendance à oublier certains médicaments ? Lesquels ?"],
    ["bpm","Entretien de recueil · Prise des médicaments","q","Vos médicaments sont-ils préparés par vous ou par quelqu’un d’autre ? Utilisez-vous un pilulier ?"],
    ["bpm","Entretien de recueil · Prise des médicaments","q","Avez-vous des difficultés à les prendre (gélules trop grosses, bouche sèche, déglutition difficile) ? Écrasez-vous ou ouvrez-vous certains médicaments ?"],
    ["bpm","Entretien de recueil · Prise des médicaments","q","Aimeriez-vous être aidé(e) dans la prise de vos médicaments ?"],
    ["bpm","Entretien de recueil · Observance (Girerd)","q","Girerd — Ce matin, avez-vous oublié de prendre votre traitement ?"],
    ["bpm","Entretien de recueil · Observance (Girerd)","q","Girerd — Depuis la dernière consultation, avez-vous déjà été en panne de médicaments ?"],
    ["bpm","Entretien de recueil · Observance (Girerd)","q","Girerd — Vous est-il arrivé de prendre votre traitement en retard par rapport à l’heure habituelle ?"],
    ["bpm","Entretien de recueil · Observance (Girerd)","q","Girerd — Vous est-il arrivé de ne pas le prendre parce que, certains jours, votre mémoire vous fait défaut ?"],
    ["bpm","Entretien de recueil · Observance (Girerd)","q","Girerd — Vous est-il arrivé de ne pas le prendre parce que vous aviez l’impression qu’il vous faisait plus de mal que de bien ?"],
    ["bpm","Entretien de recueil · Observance (Girerd)","q","Girerd — Pensez-vous que vous avez trop de médicaments à prendre ?"],
    ["bpm","Entretien de recueil · Observance (Girerd)","","Compter 1 point par réponse « non » : 6 = bonne observance, 4 ou 5 = faible observance, 3 ou moins = non-observance."],
    ["bpm","Entretien de recueil · Clôture","q","Avez-vous des questions ou des remarques ?"],
    ["bpm","Entretien de recueil · Clôture","","Rappeler le prochain rendez-vous (entretien-conseil) et le fait que le pharmacien va analyser l’ensemble des traitements."],
    ["bpm","Analyse (hors patient)","","Vérifier pour chaque médicament les posologies et les contre-indications, puis les interactions avec le logiciel métier en incluant l’automédication."],
    ["bpm","Analyse (hors patient)","a","Rechercher les associations à risque chez la personne âgée : au moins 3 psychotropes, 2 benzodiazépines, 2 antidépresseurs, 2 anti-inflammatoires, 4 antihypertenseurs, associations d’anticholinergiques."],
    ["bpm","Analyse (hors patient)","a","Repérer les médicaments à risque élevé chez la personne âgée : anticoagulants, diurétiques, IEC/ARA2, benzodiazépines, hypoglycémiants, anticholinergiques, AINS."],
    ["bpm","Analyse (hors patient)","","Conclure : observance (score de Girerd), mésusage éventuel, automédication, allergies, problèmes de forme galénique, effets indésirables, ruptures de traitement."],
    ["bpm","Analyse (hors patient)","","Pour les patients de 75 ans et plus autonomes, faire le repérage de la fragilité. Faire le point sur les vaccinations (DTP, grippe, zona, pneumocoque)."],
    ["bpm","Analyse (hors patient)","","Rédiger la fiche d’analyse et l’adresser au médecin traitant par messagerie sécurisée, puis l’enregistrer dans le DMP."],
    ["bpm","Entretien-conseil · Explications","e","Expliquer au patient le résultat de l’analyse et les points d’amélioration, avec des mots simples."],
    ["bpm","Entretien-conseil · Explications","","Remettre et commenter le plan de posologie personnalisé : médicament, dosage, horaires matin/midi/soir/coucher, durée, explications et conseils."],
    ["bpm","Entretien-conseil · Explications","e","Oubli ou double prise : ne jamais prendre en double pour rattraper un oubli. En cas de double prise, contacter rapidement le médecin traitant."],
    ["bpm","Entretien-conseil · Explications","e","Donner les conseils hygiéno-diététiques adaptés et rappeler de ne pas prendre de médicament sans avis en automédication."],
    ["bpm","Entretien-conseil · Clôture","q","Avez-vous des questions ou des inquiétudes ?"],
    ["bpm","Entretien-conseil · Clôture","","Fixer la date de l’entretien de suivi d’observance et noter la conclusion."],
    ["bpm","Entretien de suivi · Observance","q","Depuis notre dernier entretien, comment se passent vos prises ? Avez-vous appliqué le plan de posologie ?"],
    ["bpm","Entretien de suivi · Observance","q","Avez-vous eu des effets indésirables ou des difficultés (avaler, couper, horaires) ?"],
    ["bpm","Entretien de suivi · Observance","","Vérifier les acquis, noter les changements de traitement et alerter le médecin traitant si besoin."],

    ["enceinte","1 · Proposer l’entretien","e","Présenter l’objectif : sensibiliser au risque des médicaments pendant la grossesse et à l’importance de la vaccination. L’entretien est unique, à un moment choisi avec la patiente."],
    ["enceinte","1 · Proposer l’entretien","","Recevoir la patiente dans l’espace de confidentialité, sans la culpabiliser."],
    ["enceinte","2 · Médicaments et grossesse","q","Prenez-vous actuellement des médicaments, sur ordonnance ou en automédication ?"],
    ["enceinte","2 · Médicaments et grossesse","","Vérifier qu’aucun traitement en automédication n’est dangereux pour le fœtus."],
    ["enceinte","2 · Médicaments et grossesse","a","Rappeler les risques tératogènes et fœtotoxiques de certains médicaments : ne rien prendre sans avis d’un médecin, d’une sage-femme ou d’un pharmacien."],
    ["enceinte","2 · Médicaments et grossesse","","Aborder les risques à l’aide des supports ANSM (flyers pharmaciens, fiche programme de prévention des grossesses)."],
    ["enceinte","3 · Vaccination","q","Êtes-vous à jour de vos vaccins ? Avez-vous parlé de la vaccination avec votre médecin ou votre sage-femme ?"],
    ["enceinte","3 · Vaccination","e","Rappeler l’importance de la vaccination pendant la grossesse : grippe, Covid, coqueluche et VRS."],
    ["enceinte","4 · Documents","","Remettre le flyer ANSM destiné aux femmes enceintes."],
    ["enceinte","4 · Documents","","Envoyer par e-mail (espace numérique de santé de la patiente) le lien vers la page « femme enceinte » d’ameli.fr et le guide de l’Assurance Maladie sur les étapes de la grossesse."],
    ["enceinte","5 · Clôture","q","Avez-vous des questions ?"],
    ["enceinte","5 · Clôture","","Facturer l’entretien au comptoir avec la carte Vitale (code acte EFE), facturé seul, avec numéro d’identification du pharmacien en prescripteur et en exécutant."],

    ["opioides","1 · Repérer et proposer","","Identifier le patient éligible : 18 ans ou plus, antalgique opioïde de palier II, deuxième délivrance (premier renouvellement) pour une prescription de plus d’un mois. Un seul entretien valorisable par patient sur 12 mois."],
    ["opioides","1 · Repérer et proposer","","Proposer l’entretien sans culpabiliser, au moment de la délivrance, dans un espace confidentiel."],
    ["opioides","1 · Repérer et proposer","","Vérifier avant : identité et âge, médecin prescripteur, indication, médicament, dosage, posologie, durée, date de début, autres médicaments dont l’automédication."],
    ["opioides","2 · Règles de prescription","e","Tramadol, codéine, dihydrocodéine : durée maximale de prescription orale de 12 semaines (au-delà, nouvelle ordonnance). Ordonnance sécurisée. Délivrer les plus petits conditionnements adaptés."],
    ["opioides","2 · Règles de prescription","e","Le tramadol est réservé aux douleurs modérées à intenses, pour la durée la plus courte possible. Non recommandé dans la migraine."],
    ["opioides","3 · Évaluer le mésusage (POMI)","q","POMI — Avez-vous déjà pris ce médicament anti-douleur en quantité plus importante que prescrit ?"],
    ["opioides","3 · Évaluer le mésusage (POMI)","q","POMI — Avez-vous déjà pris ce médicament plus souvent que prescrit, en réduisant le délai entre deux prises ?"],
    ["opioides","3 · Évaluer le mésusage (POMI)","q","POMI — Avez-vous déjà eu besoin de faire renouveler votre ordonnance plus tôt que prévu ?"],
    ["opioides","3 · Évaluer le mésusage (POMI)","q","POMI — Un médecin vous a-t-il déjà dit que vous en preniez trop ?"],
    ["opioides","3 · Évaluer le mésusage (POMI)","q","POMI — Avez-vous déjà eu la sensation de planer ou ressenti un effet stimulant après l’avoir pris ?"],
    ["opioides","3 · Évaluer le mésusage (POMI)","a","Score POMI de 2 réponses « oui » ou plus : risque actuel de mésusage. Alerter le médecin prescripteur et le médecin traitant par messagerie sécurisée."],
    ["opioides","4 · Bon usage et sécurité","q","Combien de comprimés prenez-vous réellement par jour ? Respectez-vous les horaires et l’intervalle entre les prises ?"],
    ["opioides","4 · Bon usage et sécurité","q","Le traitement soulage-t-il suffisamment votre douleur ? Que faites-vous en cas d’oubli ou de manque de médicament ?"],
    ["opioides","4 · Bon usage et sécurité","e","Respecter strictement la prescription (dose, voie, horaires, durée) : ne pas augmenter les doses ni poursuivre sans avis médical. Prendre la dose minimale efficace."],
    ["opioides","4 · Bon usage et sécurité","e","Effets indésirables fréquents et impact sur la vie quotidienne : prudence en conduite (voiture, deux-roues) et avec les machines dangereuses."],
    ["opioides","4 · Bon usage et sécurité","e","Arrêt : diminuer progressivement la posologie pour éviter un syndrome de sevrage, et en surveiller les signes."],
    ["opioides","4 · Bon usage et sécurité","a","Attention au paracétamol associé : dose maximale de 4 g par jour chez l’adulte, en comptant les médicaments sans ordonnance."],
    ["opioides","4 · Bon usage et sécurité","e","Ne pas stocker d’opioïde : rapporter les médicaments non utilisés à la pharmacie. Ne jamais donner son traitement à une autre personne."],
    ["opioides","5 · Signes d’alerte","a","Rechercher : somnolence inhabituelle, vertiges, confusion, nausées et vomissements, constipation, difficultés respiratoires, augmentation progressive des doses, difficulté à diminuer ou arrêter, alcool, benzodiazépines ou sédatifs associés."],
    ["opioides","5 · Signes d’alerte","a","Surdosage (somnolence profonde, respiration lente ou difficile, confusion, lèvres bleutées, perte de connaissance) : appeler le 15 ou le 112, ne pas laisser la personne seule, dire qu’elle a pris un opioïde."],
    ["opioides","6 · Conclure et tracer","e","Si aucun signal inquiétant : valider la compréhension, rappeler les règles de bon usage et conseiller de revenir en cas de douleur mal contrôlée, d’effet indésirable ou de difficulté à réduire."],
    ["opioides","6 · Conclure et tracer","","Si POMI de 2 ou plus : rester factuel et non jugeant, demander l’accord du patient, transmettre les conclusions au prescripteur et au médecin traitant, ne pas modifier le traitement de sa propre initiative."],
    ["opioides","6 · Conclure et tracer","q","Pouvez-vous me redire comment vous allez prendre ce traitement ?"],
    ["opioides","6 · Conclure et tracer","","Tracer dans le dossier et le DMP : réponses POMI et score, conseils, problèmes identifiés, actions et professionnels contactés, opposition éventuelle du patient."],

    ["prevention","1 · Préparer l’entretien","","Vérifier l’âge du patient (18-25, 45-50, 60-65 ou 70-75 ans) et utiliser l’auto-questionnaire de sa tranche d’âge. Prévoir 30 à 45 minutes dans l’espace de confidentialité."],
    ["prevention","1 · Préparer l’entretien","e","Présenter le bilan prévention : faire le point sur sa santé et construire ensemble un plan personnalisé de prévention. Il est pris en charge par l’Assurance Maladie."],
    ["prevention","2 · Situation et antécédents","q","Avez-vous des enfants à la maison ? Aidez-vous un proche ? Pouvez-vous compter sur quelqu’un en cas de besoin ?"],
    ["prevention","2 · Situation et antécédents","q","Vos conditions de vie ou de travail sont-elles difficiles ou pénibles ?"],
    ["prevention","2 · Situation et antécédents","q","Avez-vous ou avez-vous eu une maladie ou un facteur de risque (hypertension, diabète, cholestérol, maladie cardiovasculaire, cancer, maladie respiratoire) ? Y a-t-il des maladies connues dans votre famille proche ?"],
    ["prevention","2 · Situation et antécédents","q","Suivez-vous un traitement ? Quand a eu lieu votre dernière prise de sang ?"],
    ["prevention","3 · Activité physique et alimentation","q","Combien de fois par semaine faites-vous au moins 30 minutes d’activité physique ?"],
    ["prevention","3 · Activité physique et alimentation","q","Combien de temps passez-vous assis(e) par jour, et devant un écran hors travail ?"],
    ["prevention","3 · Activité physique et alimentation","q","Combien de portions de fruits et légumes mangez-vous par jour ? À quelle fréquence mangez-vous des aliments gras, sucrés ou salés ?"],
    ["prevention","3 · Activité physique et alimentation","q","Avez-vous constaté une variation de poids récente, des gonflements des jambes, une toux fréquente, un essoufflement, des pauses respiratoires la nuit ?"],
    ["prevention","4 · Vaccins et dépistages","q","Êtes-vous à jour de vos vaccins et rappels ? Avez-vous votre carnet ?"],
    ["prevention","4 · Vaccins et dépistages","q","Avez-vous réalisé les dépistages recommandés pour votre âge (cancer colorectal, sein, col de l’utérus) ?"],
    ["prevention","4 · Vaccins et dépistages","q","Concernant la santé sexuelle, êtes-vous dans une situation qui justifie un dépistage ou une protection ?"],
    ["prevention","5 · Addictions","q","Consommez-vous du tabac, de l’alcool ou d’autres substances ? À quelle fréquence ?"],
    ["prevention","5 · Addictions","","Repérer les consommations à risque et proposer, si le patient le souhaite, un accompagnement ou une orientation."],
    ["prevention","6 · Plan personnalisé de prévention","","Construire avec le patient 1 à 3 objectifs prioritaires de prévention."],
    ["prevention","6 · Plan personnalisé de prévention","","Pour chaque objectif : noter les obstacles, les actions concrètes à mettre en place, et les ressources ou professionnels à consulter."],
    ["prevention","6 · Plan personnalisé de prévention","","Remettre le plan au patient et l’orienter vers un médecin si un facteur de risque ou un symptôme nécessite un avis."]
  ]$json$::jsonb) with ordinality as s(elem, ord)
join (
  select k.cle, te.id as type_id
  from (values
    ('avk', 'Entretien AVK'),
    ('aod', 'Entretien AOD'),
    ('asthme', 'Entretien asthme'),
    ('onco', 'Entretien anticancéreux oraux'),
    ('bpm', 'Bilan partagé de médication (BPM)'),
    ('enceinte', 'Entretien femme enceinte'),
    ('opioides', 'Entretien opioïdes'),
    ('prevention', 'Bilan de prévention')
  ) as k(cle, nom)
  join public.types_entretien te on te.nom = k.nom
  join public.officines o on o.id = te.officine_id and o.nom = 'Pharmacie Rome Village'
) tc on tc.cle = s.elem->>0;
